# Generated by Django 5.1.6 on 2025-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyAddedCandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('cent', models.CharField(choices=[('YG', 'Ягода'), ('MG', 'Манго'), ('AN', 'Ананас'), ('PR', 'Праскова'), ('KP', 'Къпина'), ('CH', 'Череша'), ('DN', 'Диня'), ('GF', 'Грейпфрут'), ('BR', 'Боровинка')], default='YG', max_length=100)),
                ('image', models.ImageField(upload_to='candles/')),
            ],
        ),
        migrations.AddField(
            model_name='candle',
            name='cent',
            field=models.CharField(choices=[('YG', 'Ягода'), ('MG', 'Манго'), ('AN', 'Ананас'), ('PR', 'Праскова'), ('KP', 'Къпина'), ('CH', 'Череша'), ('DN', 'Диня'), ('GF', 'Грейпфрут'), ('BR', 'Боровинка')], default='STRAWBERRY'),
            preserve_default=False,
        ),
    ]
