# Generated by Django 5.1.6 on 2025-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0004_order_recentlyaddedcandles_candle_cent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='cent',
            field=models.CharField(choices=[('Ягода', 'Ягода'), ('Манго', 'Манго'), ('Ананас', 'Ананас'), ('Праскова', 'Праскова'), ('Къпина', 'Къпина'), ('Череша', 'Череша'), ('Диня', 'Диня'), ('Грейпфрут', 'Грейпфрут'), ('Боровинка', 'Боровинка')]),
        ),
        migrations.AlterField(
            model_name='recentlyaddedcandles',
            name='cent',
            field=models.CharField(choices=[('Ягода', 'Ягода'), ('Манго', 'Манго'), ('Ананас', 'Ананас'), ('Праскова', 'Праскова'), ('Къпина', 'Къпина'), ('Череша', 'Череша'), ('Диня', 'Диня'), ('Грейпфрут', 'Грейпфрут'), ('Боровинка', 'Боровинка')], default='Ягода', max_length=100),
        ),
    ]
