# Generated by Django 5.1.6 on 2025-02-23 12:53
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0005_alter_candle_cent_alter_recentlyaddedcandles_cent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyAddedCandles',
        ),
        migrations.AddField(
            model_name='candle',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='reviews',
            field=models.IntegerField(default=39),
        ),
        migrations.AlterField(
            model_name='candle',
            name='cent',
            field=models.CharField(max_length=50),
        ),
    ]
