# Generated by Django 5.1.6 on 2025-02-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0007_candleorder_customer_delete_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
