# Generated by Django 5.1.6 on 2025-02-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0008_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
