# Generated by Django 5.1.6 on 2025-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0009_customer_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('problem', models.TextField()),
            ],
        ),
    ]
