# Generated by Django 5.1.6 on 2025-03-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0011_alter_contacts_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='promotion_price',
            field=models.FloatField(default=0),
        ),
    ]
