# Generated by Django 5.1.6 on 2025-03-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0012_candle_promotion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='candles/'),
        ),
        migrations.AddField(
            model_name='candle',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='candles/'),
        ),
        migrations.AddField(
            model_name='candle',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='candles/'),
        ),
        migrations.AddField(
            model_name='candle',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
