# Generated by Django 5.1.6 on 2025-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0013_candle_image_2_candle_image_3_candle_image_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candleorder',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
