# Generated by Django 5.1.6 on 2025-03-08 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0014_candleorder_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='candleorder',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 13, 15, 13, 988398, tzinfo=datetime.timezone.utc)),
        ),
    ]
